#!/usr/bin/env bash

set -euxo pipefail

FROM="${1}"
TO="${2-}"
if [ -z "${TO}" ]; then
  TO="$(git branch --show-current)"
fi

echo "Rebasing from ${FROM} to ${TO}"
COMMIT="$(git merge-base HEAD main)"
NUMBER_COMMITS_IN_BRANCH="$(git rev-list --count "${COMMIT}")"
echo "Reset to merge base commit: ${COMMIT} (${NUMBER_COMMITS_IN_BRANCH})"
#TODO: if NUMBER_COMMITS_IN_BRANCH != 1 do this and exit 1
#git reset --soft "$COMMIT"
#git commit --reuse-message=HEAD@{1}
