#!/usr/bin/env bash

set -euxo pipefail

#TODO: remove this
exit 1

#TODO go run idea-configuration-runner@latest \
# build_all.xml \
# build_all_tests.xml \
# TestUpdater.xml \
# TestDeckhouseReleaseController.xml \
# TestModuleReleaseController.xml \
# TestPullOverrideController.xml
#golangci-lint run
