# System-wide .bashrc file for interactive bash(1) shells.
if [ -z "$PS1" ]; then
   return
fi

PS1='\h:\W \u\$ '
# Make bash check its window size after a process completes
shopt -s checkwinsize

[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"

 if [ -z "$TMUX" ]; then
   tmux attach || tmux new
 fi


export GOPATH=$HOME/go
export PATH=$GOPATH/bin:/opt/local/bin:/usr/local/Cellar/mtr/0.92/sbin/:$PATH
